### ISSUE TITLE
Publish Fedora DevConf CZ retrospective

### ISSUE THREAD

**Issue by justwheel** [OSAS/commarch#3]
# Summary

Publish a public retrospective that summarizes the Fedora Project participation at DevConf CZ and why this is an important event for the Fedora community.

# Background

Fedora contributors are everywhere and many of our community members represent the community at events large and small, formally and informally. However, some events have special significance and DevConf CZ is one of those events. It is an important event because Fedora has participated for a long time, but also because it attracts our contributor community. It is also tied closely to Red Hat due to its proximity to the RH Brno office, making it a convenient location for Fedora contributors employed by Red Hat in Europe. So, because DevConf CZ is an important event for our community, we need to document and message on the value of the event for Fedora.

The scope of this issue is to put together a retrospective on DevConf CZ and Fedora, using a data-driven approach and offering recommendations for how Fedora can continue to use DevConf CZ as an important event for our contributor community. It also sets the stage for why we are making certain changes to the Flock 2025 planning.

# Details

There are some data sources to consider, as well as a potential roadmap for achieving this issue.

### Fedora Badges data

* [DevConf.cz 2024 Attendee](https://badges.fedoraproject.org/badge/devconf.cz-2024-attendee): 46 claims
* [DevConf.cz 2023 Attendee](https://badges.fedoraproject.org/badge/devconf.cz-2023-attendee): 31 claims
* [DevConf.cz 2022 Attendee](https://badges.fedoraproject.org/badge/devconf.cz-2022-attendee): 112 claims
* [DevConf.cz 2021 Attendee](https://badges.fedoraproject.org/badge/devconf.cz-2021-attendee): 151 claims
* [DevConf.cz 2020 Attendee](https://badges.fedoraproject.org/badge/devconf.cz-2020-attendee): 63 claims

### Fedora swag survey

A tip of the hat to @smeragoel who put together this survey and helped us get attendees to fill this out during the event:

![A bar chart showing the preferences of 49 people for their favorite swag items. The responses are used to help determine popular swag items that the Fedora Project community wishes to see. This survey was shared with attendees at DevConf CZ, a yearly open source conference in Czechia. The chart includes categories such as T-shirts, Pens, Stickers, Socks, Bags, Tech Items, Drinkware, Stress Balls, Notebooks, Pajamas, Hoodies, Fedora Geekos, Mugs, Screen Cleaners, and more. The most popular swag item is t-shirts, followed by socks, stickers, and drinkware.](https://github.com/user-attachments/assets/e8e5b215-0120-46ab-a0fa-41842143e3b9 "A bar chart showing the preferences of 49 people for their favorite swag items. The responses are used to help determine popular swag items that the Fedora Project community wishes to see. This survey was shared with attendees at DevConf CZ, a yearly open source conference in Czechia. The chart includes categories such as T-shirts, Pens, Stickers, Socks, Bags, Tech Items, Drinkware, Stress Balls, Notebooks, Pajamas, Hoodies, Fedora Geekos, Mugs, Screen Cleaners, and more. The most popular swag item is t-shirts, followed by socks, stickers, and drinkware.")

## Roadmap

- [ ] Write a thesis statement for the value of DevConf CZ to the Fedora community
- [ ] Create an outline for an article spotlighting the Fedora engagement at DevConf CZ
- [ ] Draft an article that fits the outline, use the data sources above to support the thesis statement
- [ ] Request review by Dorka Volavkova, Jason Brooks, Matthew Miller, Aoife Moloney
- [ ] Request editor review in the CommBlog
- [ ] Schedule and publish article!

# Outcome

A stronger connection is made between the Fedora community and DevConf CZ, and its role as an important event for the community is better understood by contributors and users alike.
